# Generated by Django 3.0 on 2019-12-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter a tea category (e.g. Black tea, Green tea etc.)', max_length=100)),
                ('description', models.CharField(help_text='Enter description for current category', max_length=1000)),
            ],
            options={
                'db_table': 'tCategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('price', models.FloatField(help_text='Price for 100 grams')),
                ('image_url', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'tProduct',
                'managed': False,
            },
        ),
    ]
