# Generated by Django 3.0 on 2019-12-12 03:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('catalog', '0002_auto_20191212_0340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'managed': False},
        ),
    ]
