# Generated by Django 3.0 on 2019-12-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('summa', models.FloatField()),
                ('session_key', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tOrder',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('details_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_amount', models.FloatField()),
                ('summa', models.FloatField()),
            ],
            options={
                'db_table': 'tOrder_details',
                'managed': False,
            },
        ),
    ]
